# Generated by Django 2.2.2 on 2019-06-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunes_api', '0002_auto_20190606_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tune',
            old_name='tune_body',
            new_name='melody_line',
        ),
    ]
