# Generated by Django 2.2.2 on 2019-06-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chunes_api', '0003_auto_20190606_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color_code',
        ),
    ]
