# Generated by Django 2.2.2 on 2019-06-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunes_api', '0004_remove_tag_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='key_signature',
            field=models.CharField(default='C', max_length=100),
        ),
        migrations.AlterField(
            model_name='tune',
            name='tune_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
