# Generated by Django 2.2.2 on 2019-06-06 04:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('color_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('time_signature', models.CharField(default='4/4', max_length=100)),
                ('default_note_length', models.CharField(default='1/8', max_length=100)),
                ('tune_type', models.CharField(max_length=100)),
                ('key_signature', models.CharField(max_length=100)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('fork_off', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='chunes_djapi.Tune')),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tunes', to='accounts.Profile')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='chunes_djapi.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('media', models.CharField(blank=True, max_length=255, null=True)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='accounts.Profile')),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='chunes_djapi.Tune')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='accounts.Profile')),
                ('tunes', models.ManyToManyField(blank=True, related_name='library', to='chunes_djapi.Tune')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chunes_djapi.Comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chunes_djapi.Post')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.Profile')),
            ],
        ),
    ]
