# Generated by Django 2.2.2 on 2019-06-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunes_djapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='tune_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tune',
            name='tags',
            field=models.ManyToManyField(blank=True, to='chunes_djapi.Tag'),
        ),
    ]
